name: Test Action

on: [push]

jobs:
  detect_secrets:
    runs-on: ubuntu-latest
    name: detects the secrets
    steps:
      - name: run detect secrets
        id: detect_secrets
        uses: CorrelatedLabs/detect-secrets-action@0.0.1
